<a href="https://colab.research.google.com/github/hussain0048/Python/blob/master/9_20_21Python_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Table of Content**

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ol>
        <li><a href="https://colab.research.google.com/drive/16RuGVxgCercSOghBqECW-Dz_DOEFd_t6#scrollTo=BwlGIq-fgExg">Introduction</a></li>
        <li><a href="#downloading_data">Install Jupyter Notebook</a></li>
        <li><a href="#pre-processing">Prerequisites</a></li>
        <li><a href="#setting_up_tree">Importing libraries</a></li>
        <li><a href="#modeling">Processing</a></li>
        <li><a href="#prediction">Building the model</a></li>
        <li><a href="#evaluation">Making Predictions for test data</a></li>
    </ol>
</div>
<br>
<hr>

# **1-Introduction**
Python is a very simple language, and has a very straightforward syntax. It encourages programmers to program without boilerplate (prepared) code. There are two major Python versions, Python 2 and Python 3. Python 2 and 3 are quite different. This tutorial uses Python 3, because it more semantically correct and supports newer features.

Python is a high-level programming language that Google, Facebook, NASA, and almost all other multinational companies worldwide use. Python has overtaken every language in recent years and has become the most popular and widely used programming language globally.
Its popularity on the job market has grown to the extent that companies have made Python a requirement in their job postings. According to the Times of India, Python was among the top 5 highest-paid programming languages in 2021.
But what exactly is Python, and why has it suddenly become such a sought-after language?

#**2-Why is  ‘Python’?**

Python is an interpreted, object-oriented programming language created by Guido van Rossum in 1991.
Python can be used for everything from web development to Machine learning, Artificial intelligence, and Data Science.
Unlike some other programming languages, Python does not require you to worry about syntax. Writing in Python is almost equal to written English. You have to use the proper functions or "modules" and let Python do the rest.
The easy syntax of Python makes it great for beginners who are learning how to code and seasoned developers who want to quickly create software prototypes and earn a reasonable amount of income.
Without wasting further time, let us get into the real business

#**2-Why is it called ‘Python’?[4]**
While many people assume the name Python Programming comes from something related to the Python snake, it actually comes from the TV comedy series ‘Monty Python’s Flying Circus.’ This series broadcast on the BBC channelin the United Kingdom in the 1970s and was a favorite of Guido Van Rossum’s. Because it was short, cryptic, and included the name of his favorite TV comedy show, he chose the name ‘Python.’

#**3-Python does not require a compiler[4]**
Python is a high-level, interpreted language that does not require a compiler, unlike other programming languages such as Java and C++.Python code is stored in a .pyc file, which serves as the Python engine and eliminates the need for a compiler.

#**4-Python is one of Google’s official programming languages[4]**
Python is one of the few programming languages that has been designated as an official Google language. Python became one of Google’s official programming languages due of its efficiency. It was advantageous to them because it is simple to use, even on large projects. Even YouTube is powered by Python programming.

#**5-Python is similar to English[4]**
Many people claim that Python is a simple language to learn. The fundamental reason for this claim is that Python is more similar to English than other programming languages. It’s simple to figure out what each line of code accomplishes. Everything is simple and straightforward.

#**6-Wide range of aspects[4]**
Python is a general-purpose programming language. In fact, it can be used in a wide range of coding scenarios like web development, artificial intelligence, machine learning, data analytics, internet of things and many more.

![](https://drive.google.com/uc?export=view&id=1dGhEqYFL26I3zksGS6VGWMAfO6WM8kX5
)

# **Access your PC Information using Platform Library**

In [ ]:
import platform 
# Retrun Machine Type
platform.machine()

'x86_64'

In [ ]:
# retrun computer Name
platform.node()

In [ ]:
# Return your current OS
platform.platform()

In [ ]:
# Retrun process name
platform.processor()

In [ ]:
# Retrun System release
platform.release()

In [ ]:
# Retrun OS name
platform.system()

'Linux'

In [ ]:
# Retrun process name
platform.uname()

# **IDE**

![](https://drive.google.com/uc?export=view&id=1NSev_N3lLjUQZ5NFE8Kmm0jJWDfdAA5k)

##**- Install Jupyter Notebook**[2]
n this machine learning project for beginners, we will use Jupyter Notebook for the development. Let’s see steps for the installation and configuration of Jupyter Notebook.

Using pip python package manager you can install Jupyter notebook:

In [ ]:
pip3 install notebook

And that’s it, you have installed jupyter notebook

After installing Jupyter notebook you can run the notebook server. To run the notebook, open terminal and type:

In [ ]:
jupyter notebook

It will start the notebook server at http://localhost:8888


In [ ]:
!git clone https://github.com/hussain0048/Python.git

# 1- **Hello, World!**
The simplest directive in Python is the "print" directive - it simply prints out a line (and also includes a newline, unlike in C).For example, one difference between Python 2 and 3 is the print statement. In Python 2, the "print" statement is not a function, and therefore it is invoked without parentheses. However, in Python 3, it is a function, and must be invoked with parentheses.

In [ ]:
#To print a string in Python 3, just write:
print("This line will be printed.")

In [ ]:
print("Goodbye, World!")

# 2- **Indentation**
Python uses indentation for blocks, instead of curly braces. Both tabs and spaces are supported, but the standard indentation requires standard Python code to use four spaces. For example


In [ ]:
x = 1
if x == 1:
    # indented four spaces
    print("x is 1.")

In [ ]:
x = 1
if x == 1:

# 3 - **Variables and Types**
Python is completely object oriented, and not "statically typed". You do not need to declare variables before using them, or declare their type. Every variable in Python is an object.

This tutorial will go over a few basic types of variables.


## **3.1 Numbers**
Python supports two types of numbers - integers and floating point numbers. (It also supports complex numbers, which will not be explained in this tutorial).

To define an integer, use the following syntax:

In [ ]:
myint = 7
print(myint)

In [ ]:
#To define a floating point number, you may use one of the following notations:
myfloat = 7.0
print(myfloat)
myfloats = float(7)
print(myfloats)

## 3.2- **Strings**
Strings are defined either with a single quote or a double quotes.The difference between the two is that using double quotes makes it easy to include apostrophes (whereas these would terminate the string if using single quotes)

In [ ]:
mystring = 'hello'
print(mystring)
mystring = "hello"
print(mystring)

# 4 -**Lists**
Lists are very similar to arrays. They can contain any type of variable, and they can contain as many variables as you wish. Lists can also be iterated over in a very simple manner. Here is an example of how to build a list.

In [ ]:
mylist = []
mylist.append("a")
mylist.append("b")
mylist.append("c")
print(mylist[0]) # prints 1
print(mylist[1]) # prints 2
print(mylist[2]) # prints 3

In [ ]:
# prints out 1,2,3
for x in mylist:
    print(x)

In [ ]:
#Accessing an index which does not exist generates an exception (an error).
mylist = [1,2,3]
print(mylist[10])

In [ ]:

my_list=list('abcc')

In [ ]:
my_list.index('c')

In [ ]:
my_list.reverse()

In [ ]:
my_list

In [ ]:
lst1 =[1,2,3]
list2= [4,5,6]

In [ ]:
lst1.append(list2)

In [ ]:
lst1

[1, 2, 3, [4, 5, 6]]

In [ ]:
lst1.extend (list2)

In [ ]:
lst1

[1, 2, 3, [4, 5, 6], 4, 5, 6]

# **5- Basic Operators**
This section explains how to use basic operators in Python.

## 5.1- Arithmetic Operators
Just as any other programming languages, the addition, subtraction, multiplication, and division operators can be used with numbers.

In [ ]:
number = 1 + 2 * 3 / 4.0
print(number)


2.5


In [ ]:
print(type(number))

In [ ]:
# Another operator available is the modulo (%) operator, which returns the integer remainder of the division. dividend % divisor = remainder
remainder = 11 % 3
print(remainder)

2


In [ ]:
# Using two multiplication symbols makes a power relationship.
squared = 7 ** 2
cubed = 2 ** 3
print(squared)
print(cubed)


##5.2  -Using Operators with Strings
Python supports concatenating strings using the addition operator:

In [ ]:
helloworld = "hello" + " " + "world"
print(helloworld)

hello world


In [ ]:
lotsofhellos = "hello" * 10
print(lotsofhellos)

hellohellohellohellohellohellohellohellohellohello


## 5.3- Using Operators with Lists

In [ ]:
even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]
all_numbers = odd_numbers + even_numbers
print(all_numbers)

In [ ]:
# Just as in strings, Python supports forming new lists with a repeating sequence using the multiplication operator:
print([1,2,3] * 3)

# 6- String Formatting

Python uses C-style string formatting to create new, formatted strings. The "%" operator is used to format a set of variables enclosed in a "tuple" (a fixed size list), together with a format string, which contains normal text together with "argument specifiers", special symbols like "%s" and "%d".

Let's say you have a variable called "name" with your user name in it, and you would then like to print(out a greeting to that user.)


In [ ]:
# This prints out "Hello, John!"
name = "John"
print("Hello, %s!" % name)

Hello, John!


To use two or more argument specifiers, use a tuple (parentheses):

In [ ]:
# This prints out "John is 23 years old."
name = "John"
age = 23
print("%s is %d years old." % (name, age))

Any object which is not a string can be formatted using the %s operator as well. The string which returns from the "repr" method of that object is formatted as the string. For example

In [ ]:
# This prints out: A list: [1, 2, 3]
mylist = [1,2,3]
print("A list: %s" % mylist)

Here are some basic argument specifiers you should know:

%s - String (or any object with a string representation, like numbers)

%d - Integers

%f - Floating point numbers

%.<number of digits>f - Floating point numbers with a fixed amount of digits to the right of the dot.

%x/%X - Integers in hex representation (lowercase/uppercase)

# 7-**Basic String Operations**
Strings are bits of text. They can be defined as anything between quotes:



In [ ]:
astring = "Hello world!"
astring2 = 'Hello world!'

As you can see, the first thing you learned was printing a simple sentence. This sentence was stored by Python as a string. However, instead of immediately printing strings out, we will explore the various things you can do to them. You can also use single quotes to assign a string. However, you will face problems if the value to be assigned itself contains single quotes.For example to assign the string in these bracket(single quotes are ' ') you need to use double quotes only like this

In [ ]:
astring = "Hello world!"
print("single quotes are ' '")
print(len(astring))

single quotes are ' '
12


In [ ]:
astring = "Hello world!"
print(astring.index("o"))

4


That prints out 4, because the location of the first occurrence of the letter "o" is 4 characters away from the first character. Notice how there are actually two o's in the phrase - this method only recognizes the first.

But why didn't it print out 5? Isn't "o" the fifth character in the string? To make things more simple, Python (and most other programming languages) start things at 0 instead of 1. So the index of "o" is 4.

In [ ]:
astring = "Hello world!"
print(astring.count("H"))

1


For those of you using silly fonts, that is a lowercase L, not a number one. This counts the number of l's in the string. Therefore, it should print 3.

In [ ]:
astring = "Hello world!"
print(astring[3:7])

lo w


This prints a slice of the string, starting at index 3, and ending at index 6. But why 6 and not 7? Again, most programming languages do this - it makes doing math inside those brackets easier.

If you just have one number in the brackets, it will give you the single character at that index. If you leave out the first number but keep the colon, it will give you a slice from the start to the number you left in. If you leave out the second number, it will give you a slice from the first number to the end.

You can even put negative numbers inside the brackets. They are an easy way of starting at the end of the string instead of the beginning. This way, -3 means "3rd character from the end".

In [ ]:
astring = "Hello world!"
print(astring[3:7:2])

This prints the characters of string from 3 to 7 skipping one character. This is extended slice syntax. The general form is [start:stop:step].

In [ ]:
astring = "Hello world!"
print(astring[3:7])
print(astring[3:7:1])

Note that both of them produce same output

There is no function like strrev in C to reverse a string. But with the above mentioned type of slice syntax you can easily reverse a string like this

In [ ]:
astring = "Hello world!"
print(astring[::-1])

!dlrow olleH


In [ ]:
astring = "Hello world!"
print(astring.upper())
print(astring.lower())

hese make a new string with all letters converted to uppercase and lowercase, respectively.

In [ ]:
astring = "Hello world!"
print(astring.startswith("Hello"))
print(astring.endswith("asdfasdfasdf"))

This is used to determine whether the string starts with something or ends with something, respectively. The first one will print True, as the string starts with "Hello". The second one will print False, as the string certainly does not end with "asdfasdfasdf"

In [ ]:
astring = "Hello world!"
afewwords = astring.split(" ")

This splits the string into a bunch of strings grouped together in a list. Since this example splits at a space, the first item in the list will be "Hello", and the second will be "world!".

# 8- **Conditions**
Python uses boolean variables to evaluate conditions. The boolean values True and False are returned when an expression is compared or evaluated. For example:

In [ ]:
x = 2
print(x == 2) # prints out True
print(x == 3) # prints out False
print(x < 3) # prints out True


Notice that variable assignment is done using a single equals operator "=", whereas comparison between two variables is done using the double equals operator "==". The "not equals" operator is marked as "!=".

## 8.1 - Boolean operators
The "and" and "or" boolean operators allow building complex boolean expressions, for example:

In [ ]:
name = "John"
age = 23
if name == "John" and age == 23:
    print("Your name is John, and you are also 23 years old.")

if name == "John" or name == "Rick":
    print("Your name is either John or Rick.")

## 8.2 The "in" operator
The "in" operator could be used to check if a specified object exists within an iterable object container, such as a list:

In [ ]:
name = "John"
if name in ["John", "Rick"]:
    print("Your name is either John or Rick.")

Python uses indentation to define code blocks, instead of brackets. The standard Python indentation is 4 spaces, although tabs and any other space size will work, as long as it is consistent. Notice that code blocks do not need any termination.

Here is an example for using Python's "if" statement using code blocks:

In [ ]:
statement = False
another_statement = True
if statement is True:
    # do something
    pass
elif another_statement is True: # else if
    # do something else
    pass
else:
    # do another thing
    pass

In [ ]:
x = 2
if x == 2:
    print("x equals two!")
else:
    print("x does not equal to two.")

A statement is evaulated as true if one of the following is correct: 1. The "True" boolean variable is given, or calculated using an expression, such as an arithmetic comparison. 2. An object which is not considered "empty" is passed.

Here are some examples for objects which are considered as empty: 1. An empty string: "" 2. An empty list: [] 3. The number zero: 0 4. The false boolean variable: False

## 8.3 The 'is' operator
Unlike the double equals operator "==", the "is" operator does not match the values of the variables, but the instances themselves. For example:

In [ ]:
x = [1,2,3]
y = [1,2,3]
print(x == y) # Prints out True
print(x is y) # Prints out False

True
False


##8.4-**The "not" operator**
Using "not" before a boolean expression inverts it:

In [ ]:
print(not False) # Prints out True
print((not False) == (False)) # Prints out False

True
False


#**9-Loops** 
There are two types of loops in Python, **For** and **While**.

## **9.1- For Loops** 
For loops iterate over a given sequence. Here is an example [1]

In [ ]:
primes = [2, 3, 5, 7]
for prime in primes:
    print(prime)

For loops can iterate over a sequence of numbers using the "range" and "xrange" functions. The difference between range and xrange is that the range function returns a new list with numbers of that specified range, whereas xrange returns an iterator, which is more efficient. (Python 3 uses the range function, which acts like xrange). Note that the range function is zero based[1]

In [ ]:
# Prints out the numbers 0,1,2,3,4
for x in range(5):
    print(x)

In [ ]:
# Prints out 3,4,5
for x in range(3, 6):
    print(x)

In [ ]:
# Prints out 3,5,7
for x in range(3, 8, 2):
    print(x)

## **9.5 "while" loops**
While loops repeat as long as a certain boolean condition is met. For example:



In [ ]:
# Prints out 0,1,2,3,4
count = 0
while count < 5:
    print(count)
    count += 1  # This is the same as count = count + 1

##9.6 **break" and "continue" statements**
break is used to exit a for loop or a while loop, whereas continue is used to skip the current block, and return to the "for" or "while" statement. A few examples:

In [ ]:
# Prints out 0,1,2,3,4
count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break


In [ ]:
# Prints out only odd numbers - 1,3,5,7,9
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

##**9.6-Can we use "else" clause for loops?**
unlike languages like C,CPP.. we can use else for loops. When the loop condition of "for" or "while" statement fails then code part in "else" is executed. If break statement is executed inside for loop then the "else" part is skipped. Note that "else" part is executed even if there is a continue statement.

In [ ]:
# Prints out 0,1,2,3,4 and then it prints "count value reached 5"

count=0
while(count<5):
    print(count)
    count +=1
else:
    print("count value reached %d" %(count))

# Prints out 1,2,3,4
for i in range(1, 10):
    if(i%5==0):
        break
    print(i)
else:
    print("this is not printed because for loop is terminated because of break but not due to fail in condition")

#**10-Functions**

**What are Functions?**

Functions are a convenient way to divide your code into useful blocks, allowing us to order our code, make it more readable, reuse it and save some time. Also functions are a key way to define interfaces so programmers can share their code.

**How do you write functions in Python?**

As we have seen on previous tutorials, Python makes use of blocks.
A block is a area of code of written in the format of:

block_head:

    1st block line
    
    2nd block line
    ...


Where a block line is more Python code (even another block), and the block head is of the following format: block_keyword block_name(argument1,argument2, ...) Block keywords you already know are "if", "for", and "while".

Functions in python are defined using the block keyword "def", followed with the function's name as the block's name. For example:


In [ ]:
def my_function():
    print("Hello From My Function!")

In [ ]:
def my_function_with_args(username, greeting):
    print("Hello, %s , From My Function!, I wish you %s"%(username, greeting))

In [ ]:
def sum_two_numbers(a, b):
    return a + b

##**10.1 call function**
Simply write the function's name followed by (), placing any required arguments within the brackets. For example, lets call the functions written above (in the previous example): 

In [ ]:
# Define our 3 functions
def my_function():
    print("Hello From My Function!")

In [ ]:
# print(a simple greeting)
my_function()

In [ ]:
def my_function_with_args(username, greeting):
    print("Hello, %s , From My Function!, I wish you %s"%(username, greeting))

In [ ]:
my_function_with_args("John Doe", "a great year!")


In [ ]:
def sum_two_numbers(a, b):
    return a + b

#**11-Classes and Objects**

Objects are an encapsulation of variables and functions into a single entity. Objects get their variables and functions from classes. Classes are essentially a template to create your objects.

In [ ]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

We'll explain why you have to include that "self" as a parameter a little bit later. First, to assign the above class(template) to an object you would do the following:

In [ ]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()

Now the variable "myobjectx" holds an object of the class "MyClass" that contains the variable and the function defined within the class called "MyClass"

## **11.1 Accessing Object Variables**
To access the variable inside of the newly created object "myobjectx" you would do the following:

In [ ]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()

myobjectx.variable

So for instance the below would output the string "blah":


In [ ]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()

print(myobjectx.variable)

You can create multiple different objects that are of the same class(have the same variables and functions defined). However, each object contains independent copies of the variables defined in the class. For instance, if we were to define another object with the "MyClass" class and then change the string in the variable above:

In [ ]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()
myobjecty = MyClass()

myobjecty.variable = "yackity"

# Then print out both values
print(myobjectx.variable)
print(myobjecty.variable)

##**11.2 Accessing Object Functions**
To access a function inside of an object you use notation similar to accessing a variable:

In [ ]:
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()

myobjectx.function()

We have a class defined for vehicles. Create two new vehicles called car1 and car2. Set car1 to be a red convertible worth $60,000.00 with a name of Fer, and car2 to be a blue van named Jump worth $10,000.00.

In [ ]:
# define the Vehicle class
class Vehicle:
    name = ""
    kind = "car"
    color = ""
    value = 100.00
    def description(self):
        desc_str = "%s is a %s %s worth $%.2f." % (self.name, self.color, self.kind, self.value)
        return desc_str

# your code goes here
car1 = Vehicle()
car1.name = "Fer"
car1.color = "red"
car1.kind = "convertible"
car1.value = 60000.00

car2 = Vehicle()
car2.name = "Jump"
car2.color = "blue"
car2.kind = "van"
car2.value = 10000.00

# test code
print(car1.description())
print(car2.description())

# **12 Dictionaries**

A dictionary is a data type similar to arrays, but works with keys and values instead of indexes. Each value stored in a dictionary can be accessed using a key, which is any type of object (a string, a number, a list, etc.) instead of using its index to address it.

For example, a database of phone numbers could be stored using a dictionary like this:



In [ ]:
phonebook = {}
phonebook["John"] = 938477566
phonebook["Jack"] = 938377264
phonebook["Jill"] = 947662781
print(phonebook)

Alternatively, a dictionary can be initialized with the same values in the following notation:

In [ ]:
phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}
print(phonebook)

{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781}


## **12.1 Iterating over dictionaries**

Dictionaries can be iterated over, just like a list. However, a dictionary, unlike a list, does not keep the order of the values stored in it. To iterate over key value pairs, use the following syntax:

In [ ]:
phonebook = {"John" : 938477566,"Jack" : 938377264,"Jill" : 947662781}
for name, number in phonebook.items():
    print("Phone number of %s is %d" % (name, number))

## **12.2- Removing a value**
 To remove a specified index, use either one of the following notations:

In [ ]:
phonebook = {
   "John" : 938477566,
   "Jack" : 938377264,
   "Jill" : 947662781
}
del phonebook["John"]
print(phonebook)

##**12.3 Exercise**
Add "Jake" to the phonebook with the phone number 938273443, and remove Jill from the phonebook.


In [ ]:
phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}

# write your code here
phonebook["Jake"] = 938273443
del phonebook["Jill"]

# testing code
if "Jake" in phonebook:
    print("Jake is listed in the phonebook.")
if "Jill" not in phonebook:
    print("Jill is not listed in the phonebook.")

Jake is listed in the phonebook.
Jill is not listed in the phonebook.


#**13-Modules and Packages**

In programming, a module is a piece of software that has a specific functionality. For example, when building a ping pong game, one module would be responsible for the game logic, and
another module would be responsible for drawing the game on the screen. Each module is a different file, which can be edited separately.

## **13.1 Writing modules**
Modules in Python are simply Python files with a .py extension. The name of the module will be the name of the file. A Python module can have a set of functions, classes or variables defined and implemented. In the example above, we will have two files, we will have:


In [ ]:
mygame/
mygame/game.py
mygame/draw.py

The Python script game.py will implement the game. It will use the function draw_game from the file draw.py, or in other words, thedraw module, that implements the logic for drawing the game on the screen.

Modules are imported from other modules using the import command. In this example, the game.py script may look something like this:

In [ ]:
# game.py
# import the draw module
import draw

def play_game():
    ...

def main():
    result = play_game()
    draw.draw_game(result)

# this means that if this script is executed, then 
# main() will be executed
if __name__ == '__main__':
    main()

The draw module may look something like this:

In [ ]:
# draw.py

def draw_game():
    ...

def clear_screen(screen):

n this example, the game module imports the draw module, which enables it to use functions implemented in that module. The main function would use the local function play_game to run the game, and then draw the result of the game using a function implemented in the draw module called draw_game. To use the function draw_game from the draw module, we would need to specify in which module the function is implemented, using the dot operator. To reference the draw_game function from the game module, we would need to import the draw module and only then call draw.draw_game().

When the import draw directive will run, the Python interpreter will look for a file in the directory which the script was executed from, by the name of the module with a .py prefix, so in our case it will try to look for draw.py. If it will find one, it will import it. If not, he will continue to look for built-in modules.

You may have noticed that when importing a module, a .pyc file appears, which is a compiled Python file. Python compiles files into Python bytecode so that it won't have to parse the files each time modules are loaded. If a .pyc file exists, it gets loaded instead of the .py file, but this process is transparent to the user.

## **13.2 Importing module objects to the current namespace**

We may also import the function draw_game directly into the main script's namespace, by using the from command.

In [ ]:
# game.py
# import the draw module
from draw import draw_game

def main():
    result = play_game()
    draw_game(result)

You may have noticed that in this example, draw_game does not precede with the name of the module it is imported from, because we've specified the module name in the import command.

The advantages of using this notation is that it is easier to use the functions inside the current module because you don't need to specify which module the function comes from. However, any namespace cannot have two objects with the exact same name, so the import command may replace an existing object in the namespace.

## **13.3-Importing all objects from a module**
We may also use the import * command to import all objects from a specific module, like this:

In [ ]:
# game.py
# import the draw module
from draw import *

def main():
    result = play_game()
    draw_game(result)

## **13.4 Custom import name**

We may also load modules under any name we want. This is useful when we want to import a module conditionally to use the same name in the rest of the code.

For example, if you have two draw modules with slighty different names - you may do the following:

In [ ]:
# game.py
# import the draw module
if visual_mode:
    # in visual mode, we draw using graphics
    import draw_visual as draw
else:
    # in textual mode, we print out text
    import draw_textual as draw

def main():
    result = play_game()
    # this can either be visual or textual depending on visual_mode
    draw.draw_game(result)

## **13.5 Module initialization**
The first time a module is loaded into a running Python script, it is initialized by executing the code in the module once. If another module in your code imports the same module again, it will not be loaded twice but once only - so local variables inside the module act as a "singleton" - they are initialized only once.

This is useful to know, because this means that you can rely on this behavior for initializing objects. For example:


In [ ]:
# draw.py

def draw_game():
    # when clearing the screen we can use the main screen object initialized in this module
    clear_screen(main_screen)
    ...

def clear_screen(screen):
    ...

class Screen():
    ...

# initialize main_screen as a singleton
main_screen = Screen()

## **13.6 Extending module load path**

There are a couple of ways we could tell the Python interpreter where to look for modules, aside from the default, which is the local directory and the built-in modules. You could either use the environment variable PYTHONPATH to specify additional directories to look for modules in, like this:



In [ ]:
PYTHONPATH=/foo python game.py

This will execute game.py, and will enable the script to load modules from the foo directory as well as the local directory.

Another method is the sys.path.append function. You may execute it before running an import command:

In [ ]:
sys.path.append("/foo")

This will add the foo directory to the list of paths to look for modules in as well.

## **13.6 -Exploring built-in modules**

Check out the full list of built-in modules in the Python standard library here.

Two very important functions come in handy when exploring modules in Python - the dir and help functions.

If we want to import the module urllib, which enables us to create read data from URLs, we simply import the module:

In [ ]:
# import the library
import urllib

# use it
urllib.urlopen(...)

When we find the function in the module we want to use, we can read about it more using the help function, inside the Python interpreter:



In [ ]:
help(urllib.urlopen)

## **13.7 Writing packages**

Packages are namespaces which contain multiple packages and modules themselves. They are simply directories, but with a twist.

Each package in Python is a directory which MUST contain a special file called __init__.py. This file can be empty, and it indicates that the directory it contains is a Python package, so it can be imported the same way a module can be imported.

If we create a directory called foo, which marks the package name, we can then create a module inside that package called bar. We also must not forget to add the __init__.py file inside the foo directory.

To use the module bar, we can import it in two ways

#**Python Digital Cheat Sheet**

![](https://drive.google.com/uc?export=view&id=1hbFJmUmMDLpnd4k3ASp9LqvTdflrdo1N)

In [ ]:
import foo.bar

In [ ]:
from foo import bar

In the first method, we must use the foo prefix whenever we access the module bar. In the second method, we don't, because we import the module to our module's namespace.

The __init__.py file can also decide which modules the package exports as the API, while keeping other modules internal, by overriding the __all__ variable, like so:

In [ ]:
__init__.py:

__all__ = ["bar"]

##**12-NumPy For Machine Learning**
**Reference [3]**

![](https://drive.google.com/uc?export=view&id=16akPUGgRlr-P3EJ_ienONdw-HiacwaLj)

####**12.1-Introduction to NumPy**

NumPy stands for ‘Numerical Python’. It is an open-source Python library used to perform various mathematical and scientific tasks.NumPy is one of the very first libraries in Python that makes your numerical computations easy and efficient. This course will get you acquainted (familiarize) with NumPy. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices.

####**12.2- Installing NumPy**

you can install NumPy with:

In [ ]:
conda install numpy

**or**

In [ ]:
pip install numpy

####**12.3-How to import NumPy?**

After installing NumPy, you can now use this library by importing it. To import NumPy use:

In [ ]:
import numpy as np


####**12.4-What is an array**

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.


![](https://drive.google.com/uc?export=view&id=1KidYQvwakSB5DsDSpMTWtqojlUZVRyhr)

An array is known as the central data structure of the NumPy library. Array in NumPy is called as NumPy Array.


![](https://drive.google.com/uc?export=view&id=1yvRXtvrSxdElgAbt0D54qC4h_z6LEu2p)

####**12.5- What is the difference between Python List and a Numpy Array?**

- Python list can contain elements with different data types whereas Numpy Array‘s elements are always homogeneous(same data types).

- NumPy arrays are faster and more compact than Python lists.

**Why NumPy Arrays are faster than Lists?**

- NumPy Array uses fixed memory to store data and less memory than Python lists.

- Contiguous memory allocation in NumPy Arrays.

####**12.6-Creating Arrays**

NumPy Arrays of different dimensions can be created by using ndarray(n-dimensional array). It is an array class in NumPy.The basic ndarray can be created using the numpy.array() function in NumPy.

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

**(a)1-Dimensional Array**

In [ ]:
import numpy as np
#creating 1-dimensional arrays
#creating python list
list_1 = [3,2,7]
arr_1 = np.array(list_1,dtype=np.int16)
print(arr_1)
#or 
arr_1=np.array([3,2,7])
print(arr_1)
output:
[3 2 7]
#creating array of complex number
arr_complex = np.array([1, 2, 3], dtype = complex)
print(arr_complex)
output:
[1.+0.j 2.+0.j 3.+0.j]

**(b)-Multi-Dimensional array**

In [ ]:
#creating two-dimensionsal array
list_m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #nested lists
arr_m = np.array(list_m,dtype=np.int16)
print(arr_m)
output:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

![](https://drive.google.com/uc?export=view&id=1XJ4_ttos8xhxT0QI-F35h8F1qB5QZQFd)

**you can create arrays with different Data Types (dtypes):**

- Char : np.byte

- Short : np.short

- Integer : np.short

- Long : np.int_

- Float : np.single&np.float32

- Double :np.double&np.float64

- np.int8: integer (-128 to 127)

- np.int16:integer( -32768 to 32767)

- np.int32: integer(-2147483648 to 2147483647)

- np.int64 :integer( -9223372036854775808 to 
9223372036854775807)

####**12.7-Array in NumPy also provides many functions to create different types of arrays.**

**(i)-An Array having all elements 0**

In [ ]:
#Creating an array of all zeros
arr_0 = np.zeros((2,2))  
print(arr_0)
output:
[[0. 0.]
 [0. 0.]]

**(ii)-An Array having all elements 1**

In [ ]:
# Creating an array of all ones
arr_1= np.ones((1,2))    
print(arr_1)
output:
[[1. 1.]]

**(iii)-An array with a constant**

In [ ]:
# Creating a constant array
arr_c = np.full((2,2), 7) 
print(arr_c)
output:
[[7 7]
 [7 7]]

**(iv)-Creating an array with start value, end value and number of values**

In [ ]:
arr_L = np.linspace(0, 5,7)
print(arr_L)
output:
[0.         0.83333333 1.66666667 2.5        3.33333333 4.16666667
 5.        ]
#observe here dtype('float64')

**(v)-Creating an array with start value, end value and number of values(datatypes int)**

In [ ]:
arr_a=np.arange(1, 10,1)
print(arr_a)
output:
[1 2 3 4 5 6 7 8 9]
#here dtype('int32')

**(vi)-An array filled with random values**

In [ ]:
arr_r = np.random.random((2,2))  
print(arr_r)
output:                 
[[0.05736758 0.58044299]
 [0.57759937 0.85564153]]

**(vii)-An array filled with random integers**

In [ ]:
arr_1= np.random.randint(10,100,7)  
print(arr_1)
output:                     
[43 15 15 62 31 88 69]

**(vii)-An array filled with random values(which follows Normal Distribution)**

In [ ]:
arr_n= np.random.randn(10)  
print(arr_n) 
output:
[ 0.71586489 -0.2929509   0.1952457   1.07499362  0.08089464 -0.18440427
 -0.00194278  0.2594934   1.8713812  -0.76195258]

**(viii)-Creating a 2x2 identity matrix**

In [ ]:
arr_I = np.eye(2)         Create a 2x2 identity matrix
print(arr_I)
output:
[[1. 0.]
 [0. 1.]]

**(ix)-Creating Arrays from existing data
This is useful for converting Python sequence into ndarray.
numpy.asarray(a, dtype=None ,order = None)**

In [ ]:
#converting list to ndarray 
import numpy as np
x = [1,2,3] 
a = np.asarray(x) 
print (a)
output:
[1 2 3]
# ndarray from tuple 
x_1 = (1,2,3) 
a_1 = np.asarray(x_1) 
print (a_1)
output:
[1 2 3]
# ndarray from list of tuples 
import numpy as np
x_2 = [(1,2,3),(4,5)] 
a_2 = np.asarray(x_2) 
print (a_2)
output:
[(1, 2, 3) (4, 5)]
7.Important Arrays attributes
arr.shape :It returns a tuple listing the length of the array along each dimension.
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]]) 
print (arr.shape)
output: 
(2, 3)
#resizing the above array
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)
output:
[[1 2]
 [3 4]
 [5 6]]
or 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)
Output:
[[1, 2] 
 [3, 4] 
 [5, 6]]

![](https://drive.google.com/uc?export=view&id=15-CuES39D3Mzrkg1uFWlFBv0cAPhGaVS)

**arr.size :**
- It returns the total number of elements in an array.

In [ ]:
import numpy as np 
x = np.array([[3,2,1],[4,6,1]]) 
print(x.size)
output:
6

**arr.itemsize:**
- It returns the number of bytes per element.

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.itemsize
output:
4

**arr.ndim:**
- This array attribute returns the number of array dimensions.

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.ndim
output:
2

**type(arr)**
-  This attribute is used to check the type.

In [ ]:
#for example -
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]]) 
print (arr)
output: 
[[1,2,3]
 [4,5,6]]
type(arr)
output:
numpy.ndarray

**arr.nbytes:**
- It returns the number of bytes used by the data portion of the array.

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.nbytes
output:
24

####**12.8-Indexing&Slicing**

Indexing is used to assign numbers to each element in the NumPy array or we can say it maps to the elements stored in an array. It helps to access an array element by referring to its index number.


![](https://drive.google.com/uc?export=view&id=1U8ymNI1vrmuEHWHyE2TLSgaGzhIUsUaU)

In [ ]:
import numpy as np
arr = np.arange(10)
print(arr)
output:
[0 1 2 3 4 5 6 7 8 9]
#Example-1
print(arr[7])
or 
print(arr[-3])
output:
7
#Example-2
print(arr[0:5])
or 
print(arr[0:-4])
output:
[0 1 2 3 4 5]
#Example-3
print(arr[-4:-1])
output:
[6 7 8]

Slicing is an operation used to extract a portion of elements from arrays by specifying lower and upper bound.

**arr[lower:upper:step]**

The lower bound element is included but the upper bound element is not included. The step value indicates the stride between the elements.


![](https://drive.google.com/uc?export=view&id=1U8ymNI1vrmuEHWHyE2TLSgaGzhIUsUaU)

**Slicing 1-Dimensional Array**

In [ ]:
import numpy as np 
arr = np.arange(10)
#Slicing single element
slice_arr = arr[2] 
print (slice_arr)
output:
[2]
#Slicing elements in between indexes
print (arr[2:5])
or
print (arr[-8:-5]) #using negative index
output:
[2,3,4]
#using slice(lower,upper,step) function
s = slice(2,7,2) 
print (arr[s])
output:
[2,4,6]
or
slice_arr = arr[2:7:2] 
print (slice_arr)
output:
[2,4,6]

**For slicing specific elements**

In [ ]:
x= np.array([11,12,13,14,15])
print(np.take(x, [0, 3,4]))
output:
[11 14 15]

**Omitting Indices-Omitted boundaries are assumed to be the beginning or end of the array/list. To understand better you can refer the above figure**

In [ ]:
arr=np.arange(10)
#Example-1
print(arr[:5])
output:
[0 1 2 3 4]
#Example-2
print(arr[5:])
output:
[5 6 7 8 9]
#Example-3
print(arr[::2])
output:
[0 2 4 6 8]

SyntaxError: ignored

**Slicing Multi-Dimensional Arrays
Slicing can be done in multi-dimensional arrays same as the above examples.**

In [ ]:
import numpy as np 
arr = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (arr)
output:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
#Slicing first row
print (arr[0:1])
output:
[[1 2 3]]
#slicing last 2 rows
print (arr[1:])
output:
[[3 4 5]
 [4 5 6]]
#slicing three rows and first column
print (arr[0:3,0:1])
output:
[[1]
 [3]
 [4]]
#slicing 4 from above array
print (arr[1:2,1:2])
output:
[[4]] 

![](https://drive.google.com/uc?export=view&id=1jagSjwYeNNmNsgwtNFi6aeEEQjKZeHjY)

##**12.9-Stacking & Splitting**

Stacking is used to join a sequence of same dimension arrays along a new axis.

numpy.stack(arrays,axis) : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

In [ ]:
import numpy as np
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([2, 3, 4])
arr_stack=np.stack((arr_1,arr_2),axis=0)
print(arr_stack)
print(arr_stack.shape)
output:
[[1 2 3]
 [2 3 4]]
(2,3)
arr_stack=np.stack((arr_1,arr_2),axis=1)
print(arr_stack)
print(arr_stack.shape)
output:
[[1 2]
 [2 3]
 [3 4]]
(3,2)

The axis parameter specifies the index of the new axis in the dimensions of the result.

![](https://drive.google.com/uc?export=view&id=1ZV1j1V2FD_aRr094j5dFQLyBZwIoMAmU)

**numpy.vstack(tup) :**

 Join arrays in sequence vertically (row-wise). The array formed by stacking will be at least 2-D. The arrays to be stacked must have the same shape along all but the first axis. 1-D arrays must have the same length.

**numpy.hstack(tup) :**

 Join arrays in sequence horizontally(column-wise). The arrays to be stacked must have the same shape along all but the second axis, except 1-D arrays which can be any length.

In [ ]:
# Generate random arrays
arr_1 = np.random.randint(10, size=(2, 2))
print(" arr_1\n", arr_1)
arr_2 = np.random.randint(10, size=(2, 2))
print(" arr_2\n", arr_2)
output:
 arr_1
 [[0 2]
 [7 6]]
 arr_2
 [[3 7]
 [1 4]]
# Stack arr_2 under arr_1
a=np.vstack((arr_1, arr_2))
print(a)
output:
[[0 2]
 [7 6]
 [3 7]
 [1 4]]
# Stacking  horizontally
b=np.hstack((arr_1, arr_2))
print(b)
output:
[[0 2 3 7]
 [7 6 1 4]]

![](https://drive.google.com/uc?export=view&id=1XC9sd2BodhoVrP7I90ZRCPQfPmopSICw)

**numpy.dstack(tup) :**

 Join arrays in sequence depth wise (along the third axis). The array formed by stacking will be at least 3-D. The arrays to be stacked must have the same shape along all but the third axis. 1-D or 2-D arrays must have the same shape.

In [ ]:
#continuing above commands
#stacking depth wise
c=np.dstack((arr_1, arr_2))
print(c)
output:
[[[0 3]
 [2 7]]
[[7 1]
 [6 4]]]

**numpy.column_stack(tup) :**

 It works the same as hstack and joins arrays in sequence horizontally(column-wise).

**numpy.row_stack(tup) :**

 It works the same as vstack and joins arrays in sequence vertically(row-wise).

In [ ]:
# row_stack()
a=np.row_stack((arr_1, arr_2))
print(a)
output:
[[0 2]
 [7 6]
 [3 7]
 [1 4]]
# column_stack()
b=np.column_stack((arr_1, arr_2))
print(b)
output:
[[0 2 3 7]
 [7 6 1 4]]

Splitting is used to split an array into multiple sub-arrays. It can be done using following NumPy functions.

**numpy.split(array,Indices_or_sections,axis) :**

 This function used to split an array into multiple sub-arrays of equal size. It returns a list of sub-arrays.

#**Introduction to Python** 


##**13.1-Exception Handling**


####**13.2-Exception Handling**

Exception handling is the way to avoiding the errors in a  programs
Example:-
         Let say you have a python program and you wrote 15 to 16 line code and before its work just fine Now you made some changes and may you have at line 6 and 5  error and that line 6 and 7 line command restricts your program from execution normally do this  in line 6 and 7 is an exception .
 So now we define exception handling   finding a way to avoid these errors Now may you have many questions in your mind.
1st Question : Why we needed exception handling.
2nd Question : How we can do exception handling.

1st and 2nd AnswerAnswer : before i told you exception is the obstacle which is restricting the program from execution so we use exception handling for this problem


Syntax :-

      Try:
          “ the code that rise the errors “
       Except exception :
             “The code display when errors occurs “
      Final :
           “ code you want to execute in both cases “

 In the try section we write the code where errors may occur so if it throws an error then it jumps to the exception section and in the end both are executed in the final section.


In [ ]:
print("Enter num 1 : ")
num1 = input() 
 
print("Enter num 2 : ")
num2 = input() 
 
try: 
    print("Addition of Number 1 and Number 2 = " ,  int(num1) + int(num2) )
 
except Exception as e:
    print(e)
 


##**14-Introduction to pandas**


####**14.1-what is Pandas**


Officially stands for python Data Analysis library 
It is open source 

1.  It is a tool used by data scientists to: 
2.  Read,
3.  write
4.  manipulate 
5.  Analysis the data 

####**14.2-why pandas**

 
1. It is helps you to explore and manipulate data in an    efficient manner
2. It helps you to analyze large volume of data with ease when we say large volumes   it is millions of rows/ records


**import panda as pd **

pd use for shortcut



####**1.1-Hello python** 
In this course we will learn Python for Data science.
Python was conceived by Guido van Rossum and released in 1991.
Nowadays you can use Python to bulid practically any place of software.
- Pythson is  open source.
- It is free to use.
- Python packages ,also for Data science.
- It is very easy to bulid packages in Python which code that you can share with other people to solve specific problem.
In this courde well start to bulid up your data science coding skills bit by bit ,so make sure to stick around to see  how powerful the language can be.

**Version of Python**

Currently three are two common version of python ,version 2- point -7 and 3-point-5 and later.Apart from some syntactical difference they are pretty similar, but as support for version 2 will fade over him our course focus on python 3.

**Python shell**

Python shell,a place where you can type python code immediately see your result.
In Datacamp's exercise interface this shell is embedd here.
Lets start off simple and use python as a calculator.
let me type 4 + 5 and hit enter your result is 9.
The python shell that's used here is actually not the original one we're using ipython.
Ipython is created by Fernado Perez and is part of broader jupyter ecosystem.

**Python script**

Python script are simply text files with the extension(dot)py.

- Text files-py
- List of python commands
- similar to typing in ipython shell.

The next step is submitting the answer.
You have explicity use print inside script if you and to generate output execution.
You can write the code and submit  your code will be executed.

####**1.1.1-The Python Interface** 

In the Python script on the right, you can type Python code to solve the exercises. If you hit Run Code or Submit Answer, your python script (script.py) is executed and the output is shown in the IPython Shell. Submit Answer checks whether your submission is correct and gives you feedback.

You can hit Run Code and Submit Answer as often as you want. If you're stuck, you can click Get Hint, and ultimately Get Solution.

You can also use the IPython Shell interactively by simply typing commands and hitting Enter. When you work in the shell directly, your code will not be checked for correctness so it is a great way to experiment.

- Experiment in the IPython Shell; type 5 / 8, for example.
- Add another line of code to the Python script on the top-right (not in the Shell): print(7 + 10).
- Hit Submit Answer to execute the Python script and receive feedback.


## 13 Data Analysis
    

In [ ]:
# Example, do not modify!
print(5 / 8)
# output 0.625

# Print the sum of 7 and 10
print(7+10)
# output 17

####**1.1.2-Any comments** 

Something that Hugo didn't mention in his videos is that you can add comments to your Python scripts. Comments are important to make sure that you and others can understand what your code is about.

To add comments to your Python script, you can use the # tag. These comments are not run as Python code, so they will not influence your result. As an example, take the comment on the right, # Division; it is completely ignored during execution.

In [ ]:
#Addition
print(6 + 8)

#Subtraction
print(8-5)

####**1.1.3-Python as a calculator** 

Python is perfectly suited to do basic calculations. Apart from addition, subtraction, multiplication and division, there is also support for more advanced operations such as:

Exponentiation: **. This operator raises the number to its left to the power of the number to its right. For example 4**2 will give 16.
Modulo: %. This operator returns the remainder of the division of the number to the left by the number on its right. For example 18 % 7 equals 4.
The code in the script on the right gives some examples.

In [ ]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

#**1.2-Variables and types**
**Variable**

- Specific ,case_sensitive name
- call up value through variable name
- 1.79m_68.7kg

**Reproducibility**


In [ ]:
height = 1.79
weight = 68.7
bmi = weight/height**2
print(bmi)

**Python type(1)**

**type(bmi)**

**float**

**day of week =5**

**type(day_of_week)**

**Python type(2)**



In [ ]:
x ="body mass index"
y ="this works too"
type(y)

**Python Type type(3)**



In [ ]:
2+3
'ab' + 'cd'

####**1.2.1-Variable Assignment** 

In [ ]:
# Create a variable saving
savings = 100

# Print out savings
print(savings)

####**1.2.2-Calculations with variables**
Remember how you calculated the money you ended up with after 7 years of investing $100? You did something like this:

100 * 1.1 ** 7
Instead of calculating with the actual values, you can use variables instead. The savings variable you've created in the previous exercise represents the $100 you started with. It's up to you to create a new variable to represent 1.1 and then redo the calculations!

In [ ]:
# Create a variable savings
savings = 100

# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = savings * growth_multiplier ** 7


####**1.2.3-Other variable types**
In the previous exercise, you worked with two Python data types:

int, or integer: a number without a fractional part. savings, with the value 100, is an example of an integer.
float, or floating point: a number that has both an integer and fractional part, separated by a point. growth_multiplier, with the value 1.1, is an example of a float.
Next to numerical data types, there are two other very common data types:

str, or string: a type to represent text. You can use single or double quotes to build a string.
bool, or boolean: a type to represent logical values. Can only be True or False (the capitalization is important!).

In [ ]:
# Create a variable desc
desc = "compound interest"

# Create a variable profitable
profitable = True

####**1.2.4-Operations with other types**
Hugo mentioned that different types behave differently in Python.

When you sum two strings, for example, you'll get different behavior than when you sum two integers or two booleans.

In the script some variables with different types have already been created. It's up to you to use them. New Section

In [ ]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of savings and growth_multiplier to year1
year1 = savings * growth_multiplier

# Print the type of year1
print(type(year1))

####**1.2.5-Type conversion**
Using the + operator to paste together two strings can be very useful in building custom messages.

Suppose, for example, that you've calculated the return of your investment and want to summarize the results in a string. Assuming the integer savings and float result are defined, you can try something like this:

In [ ]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

####**1.2.5-Can Python handle everything?**

Now that you know something more about combining different sources of information, have a look at the four Python expressions below. Which one of these will throw an error? You can always copy and paste this code in the IPython Shell to find out!

Possible Answers

- "I can add integers, like " + str(5) + " to strings."
- "I said " + ("Hey " * 2) + "Hey!"
- "The correct answer to this multiple choice exercise is answer number " + 2 (**correct**)
- True + False

#**1.3-Python Lists**

Learn to store, access, and manipulate data in lists: the first step toward efficiently working with huge amounts of data.

####**1.3.1-Python Data type**

- float = real number
- int = integer
- str = string text
- bool = True,False
- Each variables represents sigle value

####**1.3.2-Problem**
- Data science .many data points 
- Height of entire family

In [ ]:
height1 = 1.73
height2 = 1.68
height3 = 1.71
height4 = 1.89

- inconvenient

####**1.3.3-Python list**
[a,b,c]

[1.73,1.68,1.71,1.89]

fam = [1.73,1.68,1.71,1.89]

fam

- name a callective of values
- contain any type

####**1.3.4-Create a list**
As opposed to int, bool etc., a list is a compound data type; you can group values together:

a = "is"
b = "nice"
my_list = ["my", "list", a, b]
After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

In [ ]:
# Area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

####**1.3.5-Create list with different types**
A list can contain any Python type. Although it's not really common, a list can also contain a mix of Python types including strings, floats, booleans, etc.

The printout of the previous exercise wasn't really satisfying. It's just a list of numbers representing the areas, but you can't tell which area corresponds to which part of your house.

The code on the right is the start of a solution. For some of the areas, the name of the corresponding room is already placed in front. Pay attention here! "bathroom" is a string, while bath is a variable that represents the float 9.50 you specified earlier.

In [ ]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas






areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]


####**1.3.6-List of lists**
As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data.

Instead of creating a flat list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists. The script on the right can already give you an idea.

Don't get confused here: "hallway" is a string, while hall is a variable that represents the float 11.25 you specified earlier.

In [ ]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
           ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

         # Print out house
print(house)

# Print out the type of house
print(type(house))


#**1.4-Subsetting lists**


In [ ]:
fam = ["1iz",1.73, "emma",1.68, "mom",1.71, "dad",1.89]
fam[3]

1.68

**Similary to select the string "dad" from the list.**

In [ ]:
fam = ["1iz",1.73, "emma",1.68, "mom",1.71, "dad",1.89]
fam[6]

'dad'

**For multiple index**

In [ ]:
fam = ["1iz",1.73, "emma",1.68, "mom",1.71, "dad",1.89]
fam[3:5]

[1.68, 'mom']

####**1.4.1-Subset and conquer**
Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.

x = ["a", "b", "c", "d"]
x[1]
x[-3] # same result!
Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

####**1.4.2-Subset and calculate**
After you've extracted values from a list, you can use them to perform additional calculations. Take this example, where the second and fourth element of a list x are extracted. The strings that result are pasted together using the + operator:

x = ["a", "b", "c", "d"]
print(x[1] + x[3])

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


####1.4.3-Slicing and dicing**
Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

my_list[start:end]
The start index will be included, while the end index is not.

The code sample below shows an example. A list with "b" and "c", corresponding to indexes 1 and 2, are selected from a list x:

x = ["a", "b", "c", "d"]
x[1:3]
The elements with index 1 and 2 are included, while the element with index 3 is not.

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print out downstairs and upstairs

#**1.5-Manipulating Lists**

####**1.5.1-List Manipilating**
- Change list elements
- Add list elements
- Remove list elements

####**1.5.2-Changing list element**

In [ ]:
fam = ["1lz", 1.73, "emma", 1.68, "mom", 1.71, "dad",1.89]
fam[7]

1.89

####**1.5.3-Adding and removing elemtents**

In [ ]:
fam+["me",1.79]
fam_ext = fam+["me",1.79]
del(fam[2])
fam

['1lz', 1.73, 1.68, 'mom', 1.71, 'dad', 1.89]

####**1.5.4-Replace list elements**
Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

Use the IPython Shell to experiment with the commands below. Can you tell what's happening and why?

x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]
For this and the following exercises, you'll continue working on the areas list that contains the names and areas of different rooms in a house.

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

####**1.5.5-Extend a list**
If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator:

x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the areas list?

**Instruction**

Use the + operator to paste the list ["poolhouse", 24.5] to the end of the areas list. Store the resulting list as areas_1.
Further extend areas_1 by adding data on your garage. Add the string "garage" and float 15.45. Name the resulting list areas_2.


In [ ]:
# Create the areas list (updated version)
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

areas_2 

####**1.5.6-Inner workings of lists**
At the end of the video, Hugo explained how Python lists work behind the scenes. In this exercise you'll get some hands-on experience with this.

The Python code in the script already creates a list with the name areas and a copy named areas_copy. Next, the first element in the areas_copy list is changed and the areas list is printed out. If you hit Run Code you'll see that, although you've changed areas_copy, the change also takes effect in the areas list. That's because areas and areas_copy point to the same list.

If you want to prevent changes in areas_copy from also taking effect in areas, you'll have to do a more explicit copy of the areas list. You can do this with list() or by using [:].

**Instructions**

0 XP
Change the second command, that creates the variable areas_copy, such that areas_copy is an explicit copy of areas. After your edit, changes made to areas_copy shouldn't affect areas. Submit the answer to check this.

In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


##**1.6-Functions and Packages**

####**1.6.1-Functions**
- Nothing New!
- Type()
- Piece of reusable code
- Solvess particular task
- Call function instead of writing code yourself

####**1.6.2-Example**

In [ ]:
fam = [1.73,1.68,1.89]
fam
max(fam)

1.89

In [ ]:
tallest = max(fam)
tallest

####**1.6.3-Familiar functions**

Out of the box, Python offers a bunch of built-in functions to make your life as a data scientist easier. You already know two such functions: print() and type(). You've also used the functions str(), int(), bool() and float() to switch between data types. These are built-in functions as well.

Calling a function is easy. To get the type of 3.0 and store the output as a new variable, result, you can use the following:

result = type(3.0)
The general recipe for calling functions and saving the result to a variable is thus:

output = function_name(input)

In [ ]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


####**1.6.4-Multiple arguments**
In the previous exercise, the square brackets around imag in the documentation showed us that the imag argument is optional. But Python also uses a different way to tell users about arguments being optional.

Have a look at the documentation of sorted() by typing help(sorted) in the IPython Shell.

You'll see that sorted() takes three arguments: iterable, key and reverse.

key=None means that if you don't specify the key argument, it will be None. reverse=False means that if you don't specify the reverse argument, it will be False.

In this exercise, you'll only have to specify iterable and reverse, not key. The first input you pass to sorted() will be matched to the iterable argument, but what about the second input? To tell Python you want to specify reverse without changing anything about key, you can use =:

sorted(___, reverse = ___)
Two lists have been created for you in the editor. Can you paste them together and sort them in descending order?

Note: For now, we can understand an iterable as being any collection of objects, e.g. a List.

In [ ]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


##**1.7.1-Methods**
**Built_in Function**
- Maximum of list:max()
- Length of liat or string:len()
- Get index in list:?
- Reversing alist:?

**You can think of methods as function that "belong"python objects**

In [ ]:
#Example of method

#str(object) capitalize replace()
sister = "liz"

#float(object) bit_lenght()
#conjugate()
height = 1.73

#list index() cout()
fam = ["liz",1.73, "emma",1.68, "mom",1.71, "dad", 1.89]

####**1.7.2-List method**


In [ ]:
fam = ["liz",1,73, "emma",1,68, "mom",1.71, "dad",1.89]
fam.index("mom")# "call method index() on fam"
#To call the method,you use the dot notation,like this.

fam.count(1.71)


**Similarly,I can use the count method on the fam list to count the number of times 1-point-71 occurs in the list.**

####**1.7.3-str method**

In [ ]:
sister

'liz'

In [ ]:
sister.capitalize()

'Liz'

**You can call the method capitalize on sister,without any inputs.It returns a string where the frist letter is capitalized new.**

####**1.7.4-String Methods**
Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover them in more detail, you can always type help(str) in the IPython Shell.

A string place has already been created for you to experiment with.

In [ ]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

poolhouse
POOLHOUSE


####**1.7.5-List Methods**
Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

index(), to get the index of the first element of a list that matches its input and
count(), to get the number of times an element appears in a list.
You'll be working on the list with the area of different parts of a house: areas.



In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

##**1.8.1-Packages**
**What are packages**

We don't usually store all of our files on our computer in the same location. We use a well-organized hierarchy of directories for easier access.

Similar files are kept in the same directory, for example, we may keep all the songs in the "music" directory. Analogous to this, Python has packages for directories and modules for files.

####**1.8.2-Motivation**
- **Function and methods are powerful.**

Python functions and methods are extremely powerful:You can basically use other people's code to solve your own problems.


- **Lots of code you won't use.**

There would be tons of tons of code in there that you'll never use.


- **Maintenance problem**

Maintaning all of this code would be a real pain.



####**1.8.3-Packages**

- **Directory of python scripts**

You can think of packages as a director of python scripts.Each such script is a so-called module.

- **Module**

Modules in Python are simply Python files with a .py extension. The name of the module will be the name of the file. A Python module can have a set of functions, classes or variables defined and implemented

**Types of module**

There are two types of modulein python.

**Built in module**
- Pre installed in python.

**External module**
- Need to install using pip.



- **Script**

A Python script is a collection of commands in a file designed to be executed like a program. The file can of course contain functions and import various modules, but the idea is that it will be run or executed from the command line or from within a Python interactive shell to perform a specific task.

- **Specify function,method,type.**

Thses module specify,methods and new python types aimed at solving particular problems.

- **Thousand of packages available**

There are thousand of packages is available from internet.




**Packages for Data science**

- **Numpy**

Nympy to efficiently work with arrays.

- **Matplotlib**

Matplotlib for data visualization,and scikit-learn for mechine learning.


####**1.8.4-Install packages**

To use python packages,you'll frist have to install them on your own system and then put code in your script tp tell python that you want to use thses packages

**pip**

- A packages maintenance system for python.
- pip is the package manager for python.- 
- You can use to install pip amodule on your system.


http://pip.readthedocs.org/en/stable/installing/
You can download the file get-pip-dot-py.

- **Terminal**

Next you go to the terminal,and execute python3 get-pip-dot-py.

- **pip3 install nump**

If you install nump file.



####**1.8.5-Import packages**

Bofore you can do this,you should import the packages,or a specific module of the packages you can do this with the import statement.

To import the entire numpy packages you can do import nump,loke this.

In [ ]:
import numpy
array([1,2,3])

A commonly used function in Numpy is array.

**It take a list as input**

In [ ]:
numpy.array([1,2,3])

- **This one is correct**
- **The Numpy array is very useful to do data science.**

# **References**

[[1] Learn Python](https://www.learnpython.org/en/Conditions)

[[2] Real-Time Face Mask Detector with Python, OpenCV, Keras](https://data-flair.training/blogs/face-mask-detection-with-python/)

[3] https://medium.com/mlpoint/numpy-for-machine-learning-211a3e58b574]

[[4] Interesting Facts About Python Programming Language](https://pub.towardsai.net/8-interesting-facts-about-python-programming-language-ff8ccba88cad#3781)


[20 Great Pandas Tricks For Data Science](https://towardsdatascience.com/20-great-pandas-tricks-for-data-science-3a6daed71da0)

[Top 5 Python IDE’s For Data Science](https://preettheman.medium.com/top-python-ides-for-data-science-c49c6056cdb4)

[Best extensions for JupyterLab!!](https://jlgjosue.medium.com/best-extensions-for-jupyterlab-185ab5f3e05c)

[5 Useful Advanced Features of Python](https://python.plainenglish.io/5-useful-advanced-features-of-python-40f0d67fff84)