<a href="https://colab.research.google.com/github/hussain0048/Python/blob/master/NumPy_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Course from Beginner Level to Intermediate and Advance

# NumPy | Beginner Level

####**Chaptar 1-Introduction to NumPy**

NumPy stands for ‘Numerical Python’. It is an open-source Python library used to perform various mathematical and scientific tasks.NumPy is one of the very first libraries in Python that makes your numerical computations easy and efficient. This course will get you acquainted (familiarize) with NumPy. It contains multi-dimensional arrays and matrices, along with many high-lev[link text](https://)

**How to Install Numpy?**

In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


####**How to Import Numpy?**

In [ ]:
import numpy as np

####**What is an array**

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.
An array is known as the central data structure of the NumPy library. Array in NumPy is called as NumPy Array.

##**The Basics operations on Numpy Array**
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the
same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.
For example, the array for the coordinates of a point in 3D space, [1, 2, 1], has one axis. That axis has 3 elements
in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2,
the second axis has a length of 3.
[[1., 0., 0.],
[0., 1., 2.]]
NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the
same as the Standard Python Library class array.array, which only


**ndarray.ndim**

the number of axes (dimensions) of the array.

**ndarray.shape**

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a
matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**

the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python
types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some
examples.

**ndarray.itemsize**

the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize
8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.

**itemsize.**

ndarray.data
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we
will access the elements in an array using indexing facilities.


**An example**


In [ ]:
arr = np.arange(15).reshape(3, 5) 
# Arange function will create 15 points from 0 to 14 and then reshape will reshape it accordingly


In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
print(arr.shape)

(3, 5)


In [ ]:
print(arr.ndim)

2


In [ ]:
print(arr.dtype.name)

int64


In [ ]:
print(arr.size)

15


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


## **Array Creation**

There are several ways to create arrays.
For example, you can create an array from a regular Python list or tuple using the array function. The type of the
resulting array is deduced from the type of the elements in the sequences

In [ ]:
arr_a = np.array([2, 3, 4]) # array creation of integer data type

In [ ]:
print(arr_a)

[2 3 4]


In [ ]:
arr_a.dtype # Data Type

dtype('int64')

In [ ]:
arr_b = np.array([4.0,5.4,42.5]) # array creation with float data type
print(arr_b)
print(arr_b.dtype)


[ 4.   5.4 42.5]
float64


## **Array Creation with Builtin functions**

In [ ]:
arr_zeros = np.zeros((5,5))
arr_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr_ones= np.ones((5,5))
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr_create = np.arange(5,50, 2)
arr_create
len(arr_create)

23

##Printing Arrays

Printing array in numpy is very easy and can do it by using the builtin print function

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
• the last axis is printed from left to right,
• the second-to-last is printed from top to bottom,
• the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices

In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr = np.arange(24).reshape(2,3,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
arr = np.arange(1000)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

## Basic Mathematic Operations

In [ ]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
B = np.arange(12).reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A+B

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
A-B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
A*B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
A/B

<ipython-input-47-5d618eb3152c>:1: RuntimeWarning: invalid value encountered in true_divide
  A/B


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

## **Universal Functions**

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [ ]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1., 4.])
print(np.add(B, C))


### **Trigonometric functions**

In [ ]:
import numpy as np
x = np.linspace(-4, 4, 200)

# sin function
sin = np.sin(x)
# cosine function
cos = np.cos(x)
# tangent function
tan = np.tan(x)

In [ ]:
import matplotlib.pylab as plt
plt.style.use('dark_background')
%config InlineBackend.figure_format = 'retina' # to get high resolution images

In [ ]:
fig, (ax1, ax2, ax3) = plt.subplots(3, 1)
ax1.plot(x, sin)
ax1.set_title("sin")
ax2.plot(x, cos)
ax2.set_title("cos")
ax3.plot(x, tan)
ax3.set_title("tan")
plt.tight_layout()

# Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences

In [ ]:
a = np.arange(10)**3 # create 10 elements and multiply 3 times with itself

In [ ]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
a[2:5] # this will print the elements from 2 to 5-1

array([ 8, 27, 64])

In [ ]:
a[:6:2] = 1000 # store the value 1000 from 0 to 6 with jumps of 2
a


array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [ ]:
a[::-1] # Reverse the array a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [ ]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

# Iterating over multidimensional arrays

In [ ]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
for row in arr:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
for row in arr:
  for ro in row:
    print(ro)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [ ]:
for ele in arr.flat:
  print(ele)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Copies and Views

**No Copy at All**
Simple assignments make no copy of objects or their data


In [ ]:
a = np.array([[ 0, 1, 2, 3],
[ 4, 5, 6, 7],[ 8, 9, 10, 11]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a # No Copy at all but pointing to the same addsress
b 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b is a

True

In [ ]:
a is b

True

####**View or Shallow Copy**


In [ ]:
c = a.view()

In [ ]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c is a # will be false b/c c is not a but a shallow copy of it

False

In [ ]:
c.flags.owndata # will be false b/c c copied data from a

False

In [ ]:
c = c.reshape((2, 6)) # c matrix data will be changed after executing this cell but Matrix a will remain the same 

In [ ]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a # a will be 3 x 4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

####**Deep Copy**

The copy method makes a complete copy of the array and its data.

In [ ]:
d = a.copy() # a new array object with new data is created

In [ ]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
d is a # will be false b/c d is stand alone matrix now

False

In [ ]:
d is c # will be false b/c c is another matrix of a which is shallow copy

False

In [ ]:
d[1:2] = 100
d

array([[  0,   1,   2,   3],
       [100, 100, 100, 100],
       [  8,   9,  10,  11]])

# Functions and Methods Overview